apiVersion: v1
kind: Secret
metadata:
  name: loadgen-secret
type: Opaque
stringData:
  RMQ_USER: daddy
  RMQ_PW: rmq_pw_placeholder

  MYSQL_USER: daddy
  MYSQL_PW: mysql_pw_placeholder

  HMAC_KEY: hmac_key_placeholder

  CA_PATH: /data/load_gen/ca.pem
  CERT_PATH: /data/load_gen/han.gg.crt
  KEY_PATH: /data/load_gen/han.gg.key