kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

networking:
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6443
  disableDefaultCNI: false
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /home/daddy/apps/docker/docker_apps/kind/config/load_gen/data
    containerPath: /data/load_gen
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      certSANs:
        - "k8s.han.gg"
        - "localhost"
        - "127.0.0.1"
        - "100.75.9.6"
        - "0.0.0.0"
        - "kubernetes"
        - "kubernetes.default"
        - "kubernetes.default.svc"
        - "kubernetes.default.svc.cluster.local"
- role: worker
  extraMounts:
  - hostPath: /home/daddy/apps/docker/docker_apps/kind/config/load_gen/data
    containerPath: /data/load_gen