apiVersion: apps/v1
kind: Deployment
metadata:
  name: passenger-svc
  labels:
    app: passenger-svc
    appCode: load-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: passenger-svc
      appCode: load-generator
  template:
    metadata:
      labels:
        app: passenger-svc
        appCode: load-generator
    spec:
      containers:
      - name: passenger-svc
        image: kicapman1x/load-generator:passenger-service-rc1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: loadgen-config
        - secretRef:
            name: loadgen-secret
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        volumeMounts:
        - name: load-gen-data
          mountPath: /data/load_gen
      volumes:
      - name: load-gen-data
        persistentVolumeClaim:
          claimName: load-gen-pvc