apiVersion: apps/v1
kind: Deployment
metadata:
  name: satellite-interface
  labels:
    app: satellite-interface
    appCode: load-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: satellite-interface
      appCode: load-generator
  template:
    metadata:
      labels:
        app: satellite-interface
        appCode: load-generator
    spec:
      containers:
      - name: satellite-interface
        image: kicapman1x/load-generator:satellite-interface-rc1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: loadgen-config
        - secretRef:
            name: loadgen-secret
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        volumeMounts:
        - name: load-gen-data
          mountPath: /data/load_gen
      volumes:
      - name: load-gen-data
        persistentVolumeClaim:
          claimName: load-gen-pvc